---

- name: Ensure archive with CNI is downloaded
  get_url:
    url: https://github.com/containernetworking/plugins/releases/download/v0.8.2/cni-plugins-linux-amd64-v0.8.2.tgz
    dest: /opt/cni-plugins-linux-amd64-v0.8.2.tgz
  # checksum: "sha1:d595d3ded6499a64e8dac02466e2f5f2ce257c9f"

- name: Ensure archive with CNI is extracted
  unarchive:
    src: /opt/cni-plugins-linux-amd64-v0.8.2.tgz
    dest: /opt/cni/bin/
    remote_src: yes
    creates: /opt/cni/bin/bridge
