---
# tasks file for kubelet

- include: install.yml

- name: Check if certificates exist
  stat:
    path: /var/lib/kubelet/{{ item }}
  with_items: "{{ kubelet_certs }}"
  register: certs

- name: Configure Kubelet
  block:
  - include: configure.yml
  - include: service.yml
  when:
    - certs.results.0.stat.exists
    - certs.results.1.stat.exists
