---

- name: Get pod CIDR
  uri:
    url: http://metadata.google.internal/computeMetadata/v1/instance/attributes/pod-cidr
    method: GET
    return_content: yes
    headers:
      Metadata-Flavor: "Google"
  register: pod_cidr

- name: Configure kubelet config and present
  template:
    src: kubelet-config.yaml.j2
    dest: /var/lib/kubelet/kubelet-config.yaml

- name: Ensure kubelet systemd service is present
  template:
    src: kubelet.service.j2
    dest: /etc/systemd/system/kubelet.service

- name: just force systemd to reread configs (2.4 and above)
  systemd: daemon_reload=yes
  
- name: Ensure kubelet services is running
  service:
    name: kubelet
    enabled: yes
    state: started
