---

- name: Create systemd service
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service

- name: Ensure service is running
  service:
    name: etcd
    enabled: yes
    state: started
