---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: ubuntu:16.04
    provision:
      - apt-get -y install iproute
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        gce_lb_public_ip: 1.1.1.1
    host_vars:
      instance:
        kubernetes_pki_fetch_dest: .molecule/files/pki/
      controller-0:
        gce_private_ip: 10.240.0.2
      controller-1:
        gce_private_ip: 10.240.0.3
      controller-2:
        gce_private_ip: 10.240.0.4
      worker-0:
        gce_private_ip: 10.240.0.5
      worker-1:
        gce_private_ip: 10.240.0.6
      worker-2:
        gce_private_ip: 10.240.0.7

  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
