---
# tasks file for cri

- name: nsure archive with CRI is downloaded
  get_url:
    url: https://github.com/kubernetes-incubator/cri-containerd/releases/download/v1.0.0-alpha.0/cri-containerd-1.0.0-alpha.0.tar.gz
    dest: /opt/cri-containerd-1.0.0-alpha.0.tar.gz
    checksum: "sha1:cc7732666529e7879ddc1adfe205a42ad5b3dccf"

- name: Ensure archive with CRI is extracted
  unarchive:
    src: /opt/cri-containerd-1.0.0-alpha.0.tar.gz
    dest: /
    remote_src: yes
    creates: /usr/local/sbin/runc

- name: Ensure services are running
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - containerd
    - cri-containerd
