---

- name: Ensure systemd services for Kebernates components are present
  template:
    src: "{{ item }}.service.j2"
    dest: "/etc/systemd/system/{{ item }}.service"
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler

- name: Ensure services for Kubernates master are running and enabled
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
