---

- name: Ensure systemd services for Kebernates components are present
  template:
    src: "{{ item }}.service.j2"
    dest: "/etc/systemd/system/{{ item }}.service"
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler

- name: Ensure directory for kube-proxy is present
  file:
    path: /var/lib/kube-proxy
    state: directory
    mode: 0750

- name: Configure kube-scheduler and present
  copy:
    src: kube-scheduler.yaml
    dest: /etc/kubernetes/config/kube-scheduler.yaml

- name: just force systemd to reread configs (2.4 and above)
  systemd: daemon_reload=yes

- name: Ensure services for Kubernates master are running and enabled
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
